project:
  type: website
  output-dir: docs

website:
  title: "QUB-PsyR"
  navbar:
    logo: images/QUBlogoWsmall.png
    right:
      - text: "Intro"
        menu:
        - text: "R and RStudio"
          href: intro/intro1.html
        - text: "Running Code in R"
          href: intro/intro2.html
        - text: "Objects and Functions"
          href: intro/intro3.html
        - text: "Data Frames and Lists"
          href: intro/intro4.html
        - text: "Saving and Loading Data"
          href: intro/intro5.html
      - text: "Working with R Objects"
        menu:
        - text: "Binary Operators"
          href: working/working1.html
        - text: "Functions"
          href: working/working2.html
        - text: "Numerical Indexing"
          href: working/working3.html
        - text: "Logical Indexing"
          href: working/working4.html
        - text: "R Packages"
          href: working/working5.html
      - text: "Statistical Inference"
        menu:
        - text: "A Primer on Statistical Inference"
          href: inference/inference0.html
        - text: "The t-test"
          href: inference/inference1.html
        - text: "The ChiÂ²-test"
          href: inference/inference2.html
        - text: "Correlations"
          href: inference/inference3.html
        - text: "One-factorial Analysis of Variance"
          href: inference/inference4.html
        - text: "Two-factorial Analysis of Variance"
          href: inference/inference5.html
        - text: "Repeated measures and mixed ANOVAs"
          href: inference/inference6.html
        - text: "Simple linear regression"
          href: inference/inference7.html
        - text: "Multiple linear regression"
          href: inference/inference8.html
        - text: "Multi-level models"
          href: inference/inference9.html
      - text: "Data Visualisation"
        menu:
        - text: "Preface"
          href: graphs/graphs0.html
        - text: "Histograms"
          href: graphs/graphs1.html
        - text: "Scatterplots"
          href: graphs/graphs2.html
        - text: "Violin plots"
          href: graphs/graphs3.html
      - text: "Data Wrangling"
        menu:
        - text: "Preface"
          href: wrangling/wrangling0.html
        - text: "Extracting rows and columns"
          href: wrangling/wrangling1.html

      - text: "About"
        href: about.html


format:
  html:
    theme: 
      - cerulean
      - custom.scss

  

